language: objective-c
script: xcodebuild -target Nodelike -arch armv7
before_install:
  - brew install sloccount
  - sudo easy_install pip
after_success:
  - sudo pip install coviolations_app
  - covio
